
#
#person:
#  age: 18
#  boss: false
#  birth: 2019/11/14
#  maps: {s1: v1,s2: v2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2
#  name: 是你蝶
#spring:
#  profiles:
#    active: dev
#server:
#  port: 8081
#
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#---
#server:
#  port: 84
#spring:
#  profiles: prod
#logging:
#  level:
#    com:
#      atguigu: trace
#  file: Springboot.log